// The names perseveranza used before 3.0, in ONE place. 3.0 renamed them on purpose and reads
// none of them back: no silent fallback. What this module does with them is the minimum a
// clean break still owes the user, and the module itself never writes:
//   - a run that 2.x left ARMED in a project is pointed out by `arm` and `status`, with how to
//     close it; the old folder is never read beyond that, moved or deleted;
//   - an old environment variable that is still set is named, with its new name, by `arm` and
//     `status` (it is ignored either way);
//   - `runs` still lists and shows the archived runs 2.x wrote (read-only);
//   - the end-of-project commit never sweeps a leftover old folder into the repository;
//   - install.mjs removes the settings hooks earlier layouts left behind, and the files they
//     copied only when each is byte for byte the one a release copied (LEGACY_HASHES, computed
//     from git); the others it names and leaves to the user.
// The migration table in the CHANGELOG (3.0.0) mirrors LEGACY_ENV, and both READMEs list the
// new names: test/packaging/names.test.mjs checks the three agree.
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

// The exact sha256 of every file the manual installs of 1.x and 2.x copied under the Claude Code
// config dir (generated by scripts/legacy-hashes.mjs; test/packaging/legacy-hashes.test.mjs
// checks it against the git history).
export { LEGACY_HASHES } from './legacy-hashes.mjs';

// The state folder in a project, up to 2.x (now GATE_DIRNAME, paths.mjs).
export const LEGACY_GATE_DIRNAME = '.omc-loop';
// The run folder inside an archived run, up to 2.x (now ARCHIVE_GATE_DIRNAME, paths.mjs).
export const LEGACY_ARCHIVE_DIRNAME = 'omc-loop';
// The CLI entry point, up to 2.x (now manifest CLI_ENTRY).
export const LEGACY_CLI_ENTRY = 'src/cli/omc-loop.mjs';
// The scripts the settings hooks (settings.json "hooks") of a manual install ran up to 2.x,
// relative to the Claude Code config dir: 1.x <claude dir>/hooks/loop-drive.mjs (or .ps1), 2.x
// <claude dir>/perseveranza/src/shell/stop.mjs, session-start.mjs and activity-hook.mjs. 3.0 is a
// mod and registers none: one left behind would drive the loop a second time, so install.mjs
// removes a hook whose command runs exactly one of these files (and nothing else: a user's own
// script with a similar name stays).
export const LEGACY_SETTINGS_HOOK_SCRIPTS = ['hooks/loop-drive.mjs', 'hooks/loop-drive.ps1', 'perseveranza/src/shell/stop.mjs', 'perseveranza/src/shell/session-start.mjs', 'perseveranza/src/shell/activity-hook.mjs'];
// The same scripts as the plugin's own hooks.json named them up to 2.x (${CLAUDE_PLUGIN_ROOT}/...).
export const LEGACY_PLUGIN_HOOK_SCRIPTS = ['src/shell/stop.mjs', 'src/shell/session-start.mjs', 'src/shell/activity-hook.mjs'];
// The 1.x CLI copy a 1.x manual install put in <claude dir>/hooks/ (its command named it).
export const LEGACY_V1_CLI_FILE = 'omc-loop.mjs';
// [old, new] for every environment variable the tool read up to 2.x. The new names are the
// only ones read. PERSEVERANZA_HOME and PERSEVERANZA_LANG kept their names.
export const LEGACY_ENV = [
  ['OMC_LOOP_STALE_MS', 'PERSEVERANZA_STALE_MS'],
  ['OMC_LOOP_KILL', 'PERSEVERANZA_KILL'],
  ['OMC_LOOP_NO_NOTIFY', 'PERSEVERANZA_NO_NOTIFY'],
  ['OMC_LOOP_NO_WATCHDOG', 'PERSEVERANZA_NO_WATCHDOG'],
  ['OMC_LOOP_RESTORE', 'PERSEVERANZA_RESTORE'],
  ['OMC_LOOP_RESTORE_AFTER_MS', 'PERSEVERANZA_RESTORE_AFTER_MS'],
  ['OMC_LOOP_CLAUDE_BIN', 'PERSEVERANZA_CLAUDE_BIN'],
  ['OMC_ASK_TIMEOUT_MS', 'PERSEVERANZA_ASK_TIMEOUT_MS'],
  ['OMC_ASK_RETRIES', 'PERSEVERANZA_ASK_RETRIES'],
  ['OMC_ADVISOR_MODEL', 'PERSEVERANZA_ADVISOR_MODEL'],
  ['OMC_PROMPT_PACK', 'PERSEVERANZA_PROMPT_PACK'],
  ['OMC_ACTIVITY_HEARTBEAT_MS', 'PERSEVERANZA_ACTIVITY_HEARTBEAT_MS'],
  ['OMC_TEST_TIMEOUT_MS', 'PERSEVERANZA_TEST_TIMEOUT_MS'],
  ['OMC_HOOK_TIMEOUT_MS', 'PERSEVERANZA_HOOK_TIMEOUT_MS'],
  ['OMC_STATUSLINE_BASE_TIMEOUT_MS', 'PERSEVERANZA_STATUSLINE_BASE_TIMEOUT_MS'],
  ['OMC_NO_UPDATE_CHECK', 'PERSEVERANZA_NO_UPDATE_CHECK'],
];

// A task as it may be printed on one terminal line: a 2.x state is a file anyone could have
// written, so escape sequences (ESC, CSI, OSC...), other control characters and line breaks
// never reach the terminal. Every run of them becomes one space.
export function printable(text) {
  return String(text)
    .replace(/\u001b\[[0-?]*[ -\/]*[@-~]/g, ' ') // CSI sequences (colours, cursor moves, clears)
    .replace(/\u001b\][^\u0007\u001b]*(?:\u0007|\u001b\\)?/g, ' ') // OSC sequences (titles, links)
    .replace(/[\u0000-\u001f\u007f-\u009f\u2028\u2029]+/g, ' ') // the rest: C0, DEL, C1, line separators
    .replace(/ {2,}/g, ' ')
    .trim();
}

// The run 2.x left in the project, if any: { dir, kind: 'armed' | 'retained', task } | null.
// 'armed': its state.json is there (2.x hooks would still drive it; 3.0 never will).
// 'retained': its archive failed and 2.x kept the artifacts with the state set aside.
// A folder with neither is inert leftovers and is not reported. Read-only.
export function legacyRun(cwd) {
  const dir = join(cwd, LEGACY_GATE_DIRNAME);
  const kind = existsSync(join(dir, 'state.json')) ? 'armed'
    : existsSync(join(dir, 'state.disarmed.json')) ? 'retained' : null;
  if (!kind) return null;
  let task = '';
  try {
    const s = JSON.parse(readFileSync(join(dir, kind === 'armed' ? 'state.json' : 'state.disarmed.json'), 'utf8'));
    if (s && typeof s.task === 'string') task = printable(s.task);
  } catch { /* unreadable: the notice goes without the task */ }
  return { dir, kind, task };
}

// The lines `arm` and `status` print about it (empty: nothing to say).
export function legacyRunNotice(cwd) {
  const r = legacyRun(cwd);
  if (!r) return [];
  const what = r.kind === 'armed'
    ? `A loop armed by perseveranza 2.x is still in ${LEGACY_GATE_DIRNAME}/`
    : `A perseveranza 2.x run is retained in ${LEGACY_GATE_DIRNAME}/ after an archive failure`;
  return [
    `${what}${r.task ? ` (task: ${r.task.slice(0, 80)})` : ''}.`,
    `  Since 3.0 the loop lives in .perseveranza/: the old folder is never driven, archived or deleted by this version.`,
    `  To close it: copy what you want to keep (plan.md, notes.md, journal.jsonl), then delete ${LEGACY_GATE_DIRNAME}/ yourself;`,
    `  or, with a copy of perseveranza 2.x, archive it from this directory: node "<2.x root>/${LEGACY_CLI_ENTRY}" disarm`,
  ];
}

// The old variables that are still set in env: [old, new][]. They are NOT read.
export function legacyEnvSet(env = process.env) {
  return LEGACY_ENV.filter(([old]) => env[old] != null && env[old] !== '');
}

export function legacyEnvNotice(env = process.env) {
  const set = legacyEnvSet(env);
  if (!set.length) return [];
  return [`Ignored since 3.0 (renamed): ${set.map(([old, now]) => `${old} -> ${now}`).join(', ')}.`];
}

// The run folder inside an archived run dir: the 3.0 one, else the 2.x one, else null.
export function archivedGateDir(runDir, current) {
  for (const name of [current, LEGACY_ARCHIVE_DIRNAME]) {
    const p = join(runDir, name);
    if (existsSync(p)) return p;
  }
  return null;
}
